import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App', description: 'Generated by create next app',
}

export default function Layout({children}: {
    children: React.ReactNode
}) {
    // const className =
    return (<div className={`min-h-screen ax${inter.className} bg-gray-50 flex flex-col justify-center items-center pt-8`}>{children}</div>)
}
