import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ContextProviders from '@/contexts/ContextProviders'
import AlertDialog from '@/components/AlertDialog'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang='en' className={``}>
      <body className={`min-h-full ${inter.className} `}>
        <ContextProviders>
          {props.children}
          <AlertDialog />
        </ContextProviders>
      </body>
    </html>
  )
}
