import type { Metadata } from 'next'
import Banner from '@/components/Banner'
import { ReactNode } from 'react'
import AlertDialog from '@/components/AlertDialog'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: ReactNode }) {
  // const className =
  return (
    <>
      <Banner />
      {children}
      <AlertDialog />
    </>
  )
}
